name: coverage
on:
  push:
  pull_request:
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Calc coverage
        run: go test ./... -v -covermode=count -coverprofile=coverage.out
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.2.0
      - name: Enforce Min Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v3.0.0
        with:
          path: "coverage.lcov"
          min_coverage: 70